### ISSUE TITLE
Homebrew install Error: bindfs has been disabled because it requires FUSE!

### ISSUE THREAD

**Issue by YuhomC** [mpartel/bindfs#101]
Hiiiiii, It's my first time to post an issue on GitHub

I tried to install bindfs by`% brew install bindfs` and have fuse installed already.
I tried install fuse several times and versions across 3.10.0 to 4.1.2 both from [fuse website](https://osxfuse.github.io/archive.html) and terminal.
And upgraded my system from macOS Catalina 10.15 to macOS Big Sur 11.4.
All comes with the error
`Error: bindfs has been disabled because it requires FUSE!`

After searching it for days, I found the [reason](https://github.com/Homebrew/homebrew-core/pull/64491) here
because FUSE for macOS is no longer open source, some dependencies have been removed from  [Homebrew’s bindfs formula](https://github.com/Homebrew/homebrew-core/blob/501a773d3bffc60705a1c94a2292dec4bc870867/Formula/bindfs.rb) so on line 23 & 24 it shows:
> `on_macos do`
>`    disable! date: "2021-04-08", because: "requires FUSE"`

I've tried every method in [an issue like this](https://github.com/telepresenceio/telepresence/issues/1654) but all of them don't help.
There is another [revised formula for borg](https://github.com/borgbackup/homebrew-tap.git) seems solved the issue caused by same reason. But not sure how it works because I know little about coding.

So, is there any way to install bindfs instead of `brew install bindfs` ? 
Thanks in advance ;D

**Comment by mpartel** [comment]
You can try installing XCode, running `xcode-select --install`, then in a new shell, go to the extracted bindfs source code and run `./configure`, `make`, `sudo make install`

People have had trouble (#99, #100) installing on Big Sur recently and I don't fully understand what's going on. Things seem to break often on MacOS :|

**Comment by YuhomC** [comment]
Thank you sooooo much! It works now! 
The trouble maker lies in brew as I mentioned above. I install bindfs successfully from source as long as I don't use `brew install`.
I don not even know how to build from zip code before you told me.
To anyone completely new to command line like me, I want to mention 
first use `cd` + the unzipped code path  to go to the extracted bindfs source code
then
>   run`./configure` `make` `sudo make install`

**Comment by mpartel** [comment]
:+1:

**Comment by jdelker** [comment]
For anyone stepping over this:

The is a brew [tap provided by gromgit](https://github.com/gromgit/homebrew-fuse), which provides bindfs.

Install with `brew install gromgit/fuse/bindfs-mac`
