### ISSUE TITLE
bindfs does not respect the original permission when use `-o umask`

### ISSUE THREAD

**Issue by braindevices** [mpartel/bindfs#102]
```
bindfs 1.14.1
```

I have several files under ./, some of them are executable, some of them are not. I try to restrict the access to root `bindfs -u root -g root -o umask=077 ./ /tmp/imgs/` The problem is as long as I use umask, all the files will have exactly the same permission which is not expected.
```
$ stat -c "%a %n" a*
550 a1.cmd
440 a2.txt
660 a3.txt

/tmp/imgs# stat -c "%a %n" a*
700 a1.cmd
700 a2.txt
700 a3.txt

```
I think here we expect it will do the same thing as other fuse fs such as sshfs, which should just correctly apply the mask to make it to 500, 400 and 600

**Comment by mpartel** [comment]
This seems to be how fuse's `-o umask` works:
- https://github.com/libfuse/libfuse/blob/df499bf1ce634f6e67d4d366c4475d32143f00f0/lib/fuse.c#L1387-L1388 (fuse 2)
- https://github.com/libfuse/libfuse/blob/a1e41676e34096abe21d202f4c4e440fd1257672/lib/fuse.c#L1540-L1541 (fuse 3)

sshfs and it seems to have this same behaviour

```
$ mkdir a b
$ touch a/f
$ chmod 0440 a/f
$ sshfs -o umask=077  localhost:a b
$ stat -c "%a %n" a/f b/f
440 a/f
700 b/f
```

You should be able to achieve the desired effect with `-o perms=og-rwx`.

Closing, but feel free to reopen if I got something wrong!
