### ISSUE TITLE
fstab entry - separate file and directory permissions

### ISSUE THREAD

**Issue by marcoczen** [mpartel/bindfs#104]
Hi,

a. I refer to the doc/example at https://bindfs.org/ which shows;

```
/home/bob/stuff/website /home/bob/public_html fuse.bindfs force-user=www,perms=0000:u+rD  0 0
```

From the above , I am unclear on how to set separate permissions for files ( 664 ) and directories ( 775 )

in my server's /etc/fstab, i have;

```
/files/family_share/           /files/me/family_share           fuse.bindfs  perms=0775,force-group=family,create-for-group=family
/files/family_share/           /files/wifey/family_share        fuse.bindfs  perms=0775,force-group=family,create-for-group=family
```
Permissions of /files/family_share      is  root:root 755
Permissions of /files/me/family_share  is  root:family  ( after mounting via fstab )

Pls advise on how to set separate file ( 664 ) and directory ( 775 ) permissions via fstab 

Additionally, I have a cron script running hourly that cd into all directories and  does this;

```
find .  -type f -print0 | xargs -0 chmod 2664                            
find .  -type d -print0 | xargs -0 chmod 2775
```

If possible, i would like to remove this cron script.

Next;

b.) From the above, if i have  perms= , do we still need create-for-perms ?

Thanks All.

**Comment by mpartel** [comment]
a) Try `perms=0000:ug+rwD:u+rD`. you can leave out the `0000` if you want to preserve extra permissions, such as file executability or writability by others, from the underlying files. The `D` is what treats directories differently. See https://bindfs.org/docs/bindfs.1.html#sect13

b) If `perms` adds all the permissions you care about, then you probably don't need `create-for-perms`.

**Comment by marcoczen** [comment]
Wow ... I honestly did not think i would get a rpely ...I though i was gonna get shouted at  for not being able to understand the manual ... 

So i try ```perms=ug+rwD:o+rD (  u+rD -> o+rD ) ?```  or its really  ```perms=0000:ug+rwD:u+rD```

Note for tothers:
‘D’ (right hand side) Works like X but applies only to directories (not to executables).



Thanks x 3000

**Comment by mpartel** [comment]
Whoops, yes, `o` instead of `u` :+1: 

Sounds like that solved the problem so closing this issue.

**Comment by marcoczen** [comment]
Thanks !!!
