### ISSUE TITLE
Overall Share Size Increased After Implementing Bindfs - Normal ?

### ISSUE THREAD

**Issue by marcoczen** [mpartel/bindfs#105]
Guys,

I just implemented a bindfs  share few days ago.   

Before activating bindfs ;

```
du -hs  /family_share
224 GB
```

After using bindfs, it gives  ```294GB```. 
Thats about 70+GB. Is this normal ?

a. So whenever  i mount folders using bindfs to other locations, the data is duplicated ? 
    Or is the extra size ( 70GB )  just bindfs overhead ?       
b. If its a bindfs overhead, will it roughly be of fixed size or will it go up as the overall share size increases ?  

Note that I have implemented ChrootDirectory in /etc/ssh/sshd_config and therefore I mount  the source  folder  into      each relevant user's ChrootDirectory ? Is this wrong ? Am i supposed to just symlink ? 

Thanks.

**Comment by mpartel** [comment]
bindfs does not duplicate the data.

I'm not sure what's happening here. It might be a bug in bindfs or FUSE that causes it to report incorrect sizes somehow, but that seems unlikely, since bindfs just passes the size information through. Do you maybe use hard links somewhere? Those might not be represented in a way that `du` can deduplicate them. Does anything change if you pass `-l` to `du`?

**Comment by marcoczen** [comment]
Hi.

> bindfs does not duplicate the data.

Noted. So something is wrong with my box / my configuration ?

> I'm not sure what's happening here. It might be a bug in bindfs or FUSE that causes it to 
> report incorrect sizes somehow, but that seems unlikely, 
> since bindfs just passes the size information through. 

Versions :

```
bindfs ->  1.13.9-bp153.1.16
fuse  -> 2.9.7-3.3.1
kernel -> 5.3.18-59.10-default
OS -> openSUSE Leap 15.3
```

> Do you maybe use hard links somewhere? 

No. 


>Does anything change if you pass -l to du?

Without -l

```
du  -hs /files/family_share/
294G	 
```
With -l

```
du  -lhs /files/family_share/
294G	
```

In /etc/fstab, two ( i have about 20+ fuse.bindfs entries ) of the entries are;

```
/files/family_share/           /files/me/family_share           fuse.bindfs  perms=ug+rwD:o+rD,,force-group=family,create-for-group=family
/files/family_share/           /files/wifey/family_share        fuse.bindfs  perms=ug+rwD:o+rD,,force-group=family,create-for-group=family
```

Is the above how its done ? I mount /files/family_share in multiple locations ? This causes the data to duplicate ?
Is there a better way ?

In etc/ssh/sshd_config, the sftp match block with ChrootDirectory is;

```
Subsystem   sftp  internal-sftp  -u 0002

Match User me

   ChrootDirectory /files/me/
   ForceCommand internal-sftp -u 0002 
   PasswordAuthentication yes


Match User wifey

   ChrootDirectory /files/wifey/
   ForceCommand internal-sftp -u 0002 
   PasswordAuthentication yes
```


Is my configuration wrong ?

Thanks.

**Comment by mpartel** [comment]
Ok, I see that I misunderstood the original question. I didn't realize it's the _source directory_ that got larger.

I don't see anything wrong with that configuration, and no, bindfs doesn't copy the data to any internal storage - it just displays the source directory in a different location.

Depending on how the mounted directories are used, you might get some `.fuse_hidden...` files. See [this explanation](https://askubuntu.com/questions/493198/what-is-a-fuse-hidden-file-and-why-do-they-exist) if you see a bunch of them taking up space.

If that doesn't explain it, can you try to figure out which files take the extra space? I don't have a convenient command for you, but if you have a graphical environment on that machine, maybe run [filelight](https://apps.kde.org/filelight/) or [baobab](https://wiki.gnome.org/Apps/DiskUsageAnalyzer) before and after mounting bindfs and compare the results.

**Comment by marcoczen** [comment]
Hi, replies below ...

> Ok, I see that I misunderstood the original question. I didn't realize it's the _source directory_ that got larger.

So the overall size increased becos the data is now in multiple locations ?


> I don't see anything wrong with that configuration,

Ok. So my mounting method is correct. Good.

> and no, bindfs doesn't copy the data to any internal storage - it just displays the source directory in a different location.
> 

So with every mount point the data grows ?  So total size will be orginal_folder + newly_mounted_folders ?

> Depending on how the mounted directories are used, you might get some `.fuse_hidden...` files. 

No .fuse_hidden files so far ...
