### ISSUE TITLE
Can't chroot in with `su`

### ISSUE THREAD

**Issue by DUOLabs333** [mpartel/bindfs#109]
If I do `sudo mount --bind / test`, then `sudo chroot --userspec=$(id -u):$(id -g) test su - system`, I can log in as normal. However, doing the same with `sudo bindfs / test` fails with `su: Authentication service cannot retrieve authentication info` after trying the chroot.

**Comment by mpartel** [comment]
Try `sudo bindfs -o suid,dev ...`

**Comment by DUOLabs333** [comment]
It works, (`su system` works, `su - system` hangs).

**Comment by DUOLabs333** [comment]
Why did you reopen this?

**Comment by mpartel** [comment]
The last comment suggested there was still a problem and it was unclear to me why you closed this and #111.

**Comment by DUOLabs333** [comment]
It seems that these a problems with FUSE, not with bindfs.
