### ISSUE TITLE
`Input/output error` when accessing `/dev/pts/0`

### ISSUE THREAD

**Issue by DUOLabs333** [mpartel/bindfs#111]
I'm using `sudo bindfs -o direct_io,allow_other,dev /dev run/dev`. However, accessing `run/dev/pts/0` gives me `Input/output error`.

**Comment by DUOLabs333** [comment]
Seems to be an error with `posix_openpt (2: No such file or directory)) = 86`

**Comment by DUOLabs333** [comment]
`cat /dev/ptmx` gives `cat: /dev/ptmx: No such file or directory`

**Comment by mpartel** [comment]
Yeah, sorry, I have very little time to work on bindfs these days :disappointed: 
It seems unrealistic, possibly even technically impossible with FUSE, to make bindfs emulate magic filesystems like `/proc` and `/dev` entirely faithfully.

**Comment by DUOLabs333** [comment]
> It seems unrealistic, possibly even technically impossible with FUSE, to make bindfs emulate magic filesystems like /proc and /dev entirely faithfully.

Yes, it seems that for some reason, FUSE does not react well with devpts.

**Comment by DUOLabs333** [comment]
Interestingly, even with `sudo bindfs -odev /dev test`, `test/pts/ptmx`, still gets `Permission Denied`.

**Comment by DUOLabs333** [comment]
> Yes, it seems that for some reason, FUSE does not react well with devpts.

I take that back, that's not why. Apparently, FUSE messes up when dealing with character special files.
