### ISSUE TITLE
no such file or directory: ./configure

### ISSUE THREAD

**Issue by rgaufman** [mpartel/bindfs#115]
I'm trying to follow the installation instructions:

```
$ git clone https://github.com/mpartel/bindfs.git
$ cd bindfs
$ ./configure
zsh: no such file or directory: ./configure
$ ls
autogen.sh  ChangeLog  configure.ac  COPYING  Makefile.am  README.md  releasescript  src  test-all.sh  tests  TODO  vagrant
```

Any ideas?

**Comment by mpartel** [comment]
If you clone from the repo rather than downloading a release, you need to run `./autogen.sh` first. That needs (at least) `autoconf`, `automake` and `libtool` to be installed.

I should have mentioned this in the readme. Fixing.
