### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by guglovich** [mpartel/bindfs#116]
`./autogen.sh: строка 3: autoreconf: команда не найдена`

Which makes sense in principle, because the repository is cloned and the autoreconf file is not there.

**Comment by mpartel** [comment]
It's a command you need to install on your system. I think most distros have it in a package called `autoconf`. You'll also need at least `automake` and `libtool`.

**Comment by guglovich** [comment]
It's been a long time since I've seen it, I had everything on `make`.
