### ISSUE TITLE
Req: compression, encryption?

### ISSUE THREAD

**Issue by xiota** [mpartel/bindfs#119]
fusecompress is no longer developed and has some serious bugs that make it unusable.  Since it looks like a primitive bindfs + compression, maybe compression could be added to bindfs?  Maybe also encryption?

**Comment by mpartel** [comment]
I'd like bindfs's mission to be limited to metadata, not file contents. That's somewhat arbitrary, I know, but it keeps the featureset at least somewhat coherent. Actually, yours might be the first request ever in 15(!) years for bindfs to affect file contents :)

Also, I have very little time to work on bindfs these days :/
