### ISSUE TITLE
Mount fails when using resolve-symlinks and the name of the source directory starts with the name of the mountpoint.

### ISSUE THREAD

**Issue by 1-eric** [mpartel/bindfs#122]
When the name of the mountpoint (`abc`) is the same as the first character(s) of the name of the source directory (`abcdef`), mounting will fail when using the `resolve-symlinks` option.

Examples that will fail:
`bindfs --resolve-symlinks abcdef abc`
`bindfs --resolve-symlinks xdir x`

**Comment by mpartel** [comment]
Thanks! Fix released as version 1.17.1.
