### ISSUE TITLE
Failed to resolve mount point on MacOS / Ventura

### ISSUE THREAD

**Issue by OverHealz** [mpartel/bindfs#123]
mkdir aa
mkdir bb
bindfs aa bb

gives:
Failed to resolve mount point `bb': No such file or directory

**Comment by mpartel** [comment]
My MacMini is too old for Ventura :/

**Comment by slonopotamus** [comment]
bindfs works perfectly on my side. Ventura, M1, both through fuse-t and macFUSE.

**Comment by mpartel** [comment]
Thanks, closing.
