### ISSUE TITLE
no package Bindfs available 

### ISSUE THREAD

**Issue by fafa92** [mpartel/bindfs#129]
Hi,
I am trying to use the Bindfs package for Centos disto, It seems that it cannot find it. Is this package support only Ubuntu distribution or other ones too? I appreciate any help with this.

**Comment by mpartel** [comment]
Which version of CentOS? What have you tried?

Bindfs is packaged for at least some versions of CentOS. If it's not available, you can install FUSE (package `fuse3-devel` or `fuse-devel` I believel) and build from source as shown in the readme.

**Comment by fafa92** [comment]
I am running CentOS 7, I will give fuse3 a try too. Is BindFS only working for local storage on the system? or it is also supporting NFS-mounted storage to the system?

**Comment by mpartel** [comment]
Looks like CentOS 7 is so old that it doesn't have bindfs, but you can install `fuse-devel` and compile bindfs yourself.

I've never tried bindfs with NFS (either mouting on top of an NFS mount or exporting a bindfs over NFS). In #78 someone tried exporting a directory with a bindfs mount as a subdirectory, and that required a workaround.
