### ISSUE TITLE
Unable to listen to unix domain socket inside bindfs mount on macOS

### ISSUE THREAD

**Issue by slonopotamus** [mpartel/bindfs#132]
Way to reproduce:

(as root)

1. macOS Ventura + macFUSE 4.5.0 + bindfs 1.17.3
```
$ mkdir a
$ mkdir b
$ bindfs a b
$ nc -U b/sock -l
nc: Invalid argument
$ nc -U a/sock -l
<works>
```
2. macOS Ventura + fuse-t 1.0.23 + bindfs 1.17.3
```
$ mkdir a
$ mkdir b
$ bindfs a b
$ nc -U b/sock -l
nc: Input/output error
$ nc -U a/sock -l
<works>
```
If this issue is not caused by bindfs, my apologies, will report to macFUSE/fuse-t.

**Comment by mpartel** [comment]
Works on Linux, so appears to be a limitation of MacOS or fuse-t.

**Comment by slonopotamus** [comment]
Reported to:

* https://github.com/macos-fuse-t/fuse-t/issues/31
* https://github.com/osxfuse/osxfuse/issues/962

**Comment by slonopotamus** [comment]
Output of `bindfs -d -f ...` produced during `nc -U <path> -l`:

```
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 405
getattr /
   unique: 2, success, outsize: 136
unique: 3, opcode: GETXATTR (22), nodeid: 1, insize: 77, pid: 405
getxattr / com.apple.FinderInfo 32 0
   unique: 3, success, outsize: 48
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 111
getattr /
   unique: 2, success, outsize: 136
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 45, pid: 698
LOOKUP /sock
getattr /sock
   unique: 3, error: -2 (No such file or directory), outsize: 16
unique: 2, opcode: MKNOD (8), nodeid: 1, insize: 61, pid: 698
mknod /sock 0140755 0x0 umask=0000
   unique: 2, error: -22 (Invalid argument), outsize: 16
```

**Comment by slonopotamus** [comment]
If I read this correctly, the issue is actually in `mknod` implementation of `bindfs`?

**Comment by slonopotamus** [comment]
In https://github.com/macos-fuse-t/fuse-t/issues/31, I was given this link: https://libfuse.github.io/doxygen/example_2passthrough__helpers_8h_source.html. `mknod` in bindfs doesn't currently have any special handling for `S_ISSOCK`. Maybe it should?

**Comment by slonopotamus** [comment]
@mpartel what do you think?

My current understanding is that
1. There's missing functionality in fuse-t: it doesn't call `mknod` at all
2. There's missing support for `S_ISSOCK` in bindfs `mknod` implementation
3. macFUSE works properly

I suggest reopening this issue and will try to fix №2 (and send a PR).

**Comment by mpartel** [comment]
Yes, that seems likely. Thanks! And apologies, this week it's especially difficult for me to anything mac-related.

**Comment by slonopotamus** [comment]
See https://github.com/mpartel/bindfs/pull/133. With those fixes, I'm able to talk with `nc` over AF_UNIX socket created inside bindfs-mounted dir.
