### ISSUE TITLE
ACLs on MacOS

### ISSUE THREAD

**Issue by Victorious3** [mpartel/bindfs#137]
Currently I get the following error message when trying to set ACLs via bindfs:

```
% chmod +a "xadmin allow append" test
chmod: Failed to set ACL on file 'test': Operation not supported
```

**Comment by Victorious3** [comment]
I was missing extended_security in the fuse options. Sorry for the spam.

**Comment by mpartel** [comment]
I wonder if that option should be on by default :thinking:
Are you aware of any downside?

**Comment by Victorious3** [comment]
Not that I know of. It seems to work fine.
