### ISSUE TITLE
configure: error: FUSE not found on Mac 13.5.1

### ISSUE THREAD

**Issue by rgaufman** [mpartel/bindfs#138]
I installed MacFuse from https://osxfuse.github.io - version 4.5.0 (and jumped through hoops to allow the kernel module, etc).

I downloaded binds 1.17.4 but when I run configure, it won't find FUSE - any ideas?

```
$ ./configure
...
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin22.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for sys/file.h... yes
checking for lutimes... yes
checking for utimensat... yes
checking for setxattr... yes
checking for getxattr... yes
checking for listxattr... yes
checking for removexattr... yes
checking for lsetxattr... no
checking for lgetxattr... no
checking for llistxattr... no
checking for lremovexattr... no
checking for pkg-config... no
checking for fuse3 >= 3.4.0... no
checking for fuse >= 2.9.0... no
checking for fuse >= 2.8.0... no
checking for fuse-t >= 1.0.0... no
configure: error: FUSE not found
```

**Comment by mpartel** [comment]
> checking for pkg-config... no

You might need [pkg-config](https://formulae.brew.sh/formula/pkg-config#default).

Alternatively, try installing XCode and then `xcode-select --install`

If those don't help, then MacFuse's headers/library might not be found by the developer tools for whatever reason.
You may want to try [installing MacFuse via Homebrew](https://formulae.brew.sh/cask/macfuse#default) or perhaps try [fuse-t](https://www.fuse-t.org/).

**Comment by rgaufman** [comment]
Ah, you are right, once I ran brew install pkg-config, it compiled and seems to be working, thank you!

**Comment by mpartel** [comment]
:ballot_box_with_check:  Improved installation instructions on webpage and readme

**Comment by rgaufman** [comment]
Thank you, unfortunately it is not working :( 

I ran:

```
bindfs /Volumes/Drive1_2TB/iCloud /Users/hackeron/Library/Mobile\ Documents
bindfs /Volumes/Drive1_2TB/Messages /Users/hackeron/Library/Messages
```

It seems to be working, but when I turn iCloud or iMessage on, it just refuses to write anything there and the apps just hang, not sure why :(

**Comment by mpartel** [comment]
No idea, sorry, I barely ever use macs :/
`fuse-t` might be worth a try, since a good chunk of bindfs issues have turned out to be underlying FUSE issues.
