### ISSUE TITLE
homebrew: Unsatisfied requirements failed this build.

### ISSUE THREAD

**Issue by jochne** [mpartel/bindfs#139]
$ brew install bindfs
bindfs 1.14.8 is already installed but outdated (so it will be upgraded).
bindfs: Linux is required for this software.
libfuse: Linux is required for this software.
Error: bindfs: Unsatisfied requirements failed this build.

**Comment by mpartel** [comment]
Whoops, didn't notice that the Homebrew build is Linux only. Removed the reference from the web page. Thanks!

Guess you need to install from source on MacOS. There is also a MacPorts port but that looks unmaintained.

**Comment by jochne** [comment]
> 

got an solution for those who need to brew install bindfs on mac: https://github.com/Homebrew/homebrew-core/issues/141445#issuecomment-1706557629
