### ISSUE TITLE
1.17.6 no longer compiles on CentOS 7

### ISSUE THREAD

**Issue by mathiasaerts** [mpartel/bindfs#147]
Trying to compile the latest version 1.17.6 fails on CentOS 7 results in the following error:
```
bindfs.o: In function `bounded_add':
/opt/bindfs/bindfs-1.17.6/src/bindfs.c:685: undefined reference to `__builtin_add_overflow'
collect2: error: ld returned 1 exit status
make[2]: *** [bindfs] Error 1
make[2]: Leaving directory `/opt/bindfs/bindfs-1.17.6/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/bindfs/bindfs-1.17.6'
make: *** [all] Error 2
```

It seems that `__builtin_add_overflow` is simply not supported in the default GCC version 4.8.5.

**Comment by mpartel** [comment]
True. I recommend CentOS 7 users who can't use a newer compiler to keep using 1.17.4. Versions 1.17.5 and .6 only improved a specific niche use case.

With CentOS 7 reaching EOL next June, I didn't think it worthwhile to implement my own potentially buggy version of that function.

Thanks for reporting - I didn't think anyone on such an old distro would be interested in newer bindfs versions, but it's good to have this issue filed in case you're not the only one.
