### ISSUE TITLE
Get the source dir of a bindfs mount

### ISSUE THREAD

**Issue by calind** [mpartel/bindfs#15]
Is there any way to find the source of a bindfs mount? eg. if I mount a folder as bindfs `# bindfs /foo /bar` is there a way to find the source dir of `/bar` ?

**Comment by tyll** [comment]
afaics bindfs could add the source of the mount to /etc/mtab by adding ```-ofsname=/path/to/src``` (see man mount.fuse) to the fuse opts.

**Comment by mpartel** [comment]
Good find! Done. Thanks!
