### ISSUE TITLE
Show contents of test-suite.log if there is an error

### ISSUE THREAD

**Issue by tyll** [mpartel/bindfs#26]
If "make check" errors, it only shows that errors might be in the log file instead of just showing the log file. This makes it harder to get the actual error message if a build system is used that does not allow to get the log file directly, e.g. on Fedora. Therefore  please consider just showing the error directly.

**Comment by mpartel** [comment]
Yeah, some new version of autoconf/automake changed it to be this way and I haven't found a clean way to change it back. I find it a bit annoying as well.

Would it be reasonable to work around this by configuring your build system to do something like this?

    /bin/sh -c 'if make check; then true; else cat tests/test-suite.log; exit 1; fi'
    /bin/sh -c 'if sudo make check; then true; else cat tests/test-suite.log; exit 1; fi'

**Comment by tyll** [comment]
If it is not easily possible, the workaround is fine by me. I already used it to figure out test failures (it was just because of missing dependencies). Btw. testing as root is not possible in Fedora's build environment.

**Comment by mpartel** [comment]
Ok, it was fairly easy after all, I just messed up the syntax on my first try.

**Comment by tyll** [comment]
thank you
