### ISSUE TITLE
can't see full folder

### ISSUE THREAD

**Issue by ghostwheel** [mpartel/bindfs#29]
I'm using bindfs on an android tablet (arm), running debian on linux deploy (which means chroot).
I tried both the debian package, and compiled bindfs myself, and I'm seeing the same problem:
In a directory that I mount, which is quite big, I only see some of the files and directories in some of the subdirectories (94 in one case, 81 in a second case).
The command I use is
bindfs --map=root/android:@aid_sdcard_r/@android /mnt/extSdCard /mnt/bindsd1

I can't see anything special in the debugging output. Here's the end, after mounting and ls on a dir with problems.
--
LOOKUP /dropbox full/file2.pdf
getattr /dropbox full/file2.pdf
 NODEID: 82
 unique: 167, success, outsize: 144
unique: 168, opcode: GETXATTR (22), nodeid: 82, insize: 68, pid: 20300
getxattr /dropbox full/file2.pdf security.capability 20
 unique: 168, error: -95 (Operation not supported), outsize: 16
unique: 169, opcode: LOOKUP (1), nodeid: 2, insize: 106, pid: 20300
LOOKUP /dropbox full/Preview of \u201cMicrosoft Word - file1.doc\u201d.pdf
getattr /dropbox full/Preview of \u201cMicrosoft Word - file1.doc\u201d.pdf
 NODEID: 83
 unique: 169, success, outsize: 144
unique: 170, opcode: GETXATTR (22), nodeid: 83, insize: 68, pid: 20300
getxattr /dropbox full/Preview of \u201cMicrosoft Word - file1.doc\u201d.pdf security.capability 20
 unique: 170, error: -95 (Operation not supported), outsize: 16
unique: 171, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 20300
readdir[32521736] from 10623
 unique: 171, success, outsize: 16
unique: 172, opcode: RELEASEDIR (29), nodeid: 2, insize: 64, pid: 0
releasedir[32521736] flags: 0x0
 unique: 172, success, outsize: 16
--

**Comment by ghostwheel** [comment]
I tried the fix mentioned in 
https://github.com/mpartel/bindfs/pull/28/files
and that fixed this problem.

**Comment by mpartel** [comment]
#28 merged, thanks for reporting and trying it.
