### ISSUE TITLE
Failure to create-with-perms=g+D

### ISSUE THREAD

**Issue by ReubenM** [mpartel/bindfs#30]
I'm trying to set up a bindfs mount that is set to create new directories with execute permissions on directories for the group owner. I've tried multiple different ways to set that permission, without any luck. Setting permissions on the files works, but not the execute bit on directories.

This is with a linux system, bindfs-1.13.1, fuse-2.9.5

I'm trying to have this mount in fstab:
```
/public  /home/hpstream/Public  fuse.bindfs  create-with-perms=g+rwD,create-for-user=nobody,create-for-group=nobody,force-user=hpstream,force-group=hpstream  1 3
```

**Comment by mpartel** [comment]
Sorry, I wasn't able to reproduce this. To narrow down the problem, could you try the following and paste the output from both terminals here?

Terminal 1:

    mkdir a b
    bindfs -d --create-with-perms=g+rwD a b

Terminal 2:

    umask 0077
    mkdir b/dir
    ls -l a

It may be helpful to repeat the test with a bindfs compiled with `./configure --enable-debug-output && make` and run `./src/bindfs` in terminal 1 instead.

**Comment by ReubenM** [comment]
Ugh. Never mind. I figured out that the ACL default mask of the mirrored directory was the issue.
