### ISSUE TITLE
building on arm64 fails: SYS_getdents is not available

### ISSUE THREAD

**Issue by jackyf** [mpartel/bindfs#43]
Hello,

The latest version doesn't compile on arm64 (aka AArch64), because there is no SYS_getdents syscall (used in tests/test_dir_rewind.c) available, there is only SYS_getdents64:

$ grep -Ir SYS_getdents /usr/include/
/usr/include/aarch64-linux-gnu/bits/syscall.h:#define SYS_getdents64 __NR_getdents64
/usr/include/aarch64-linux-gnu/bits/syscall.h:#define SYS_getdents64 __NR_getdents64

**Comment by mpartel** [comment]
Fixed in 1.13.5.
