### ISSUE TITLE
bindfs does not support devices

### ISSUE THREAD

**Issue by itamarst** [mpartel/bindfs#52]
Ubuntu 16.04, bindfs 1.12.6 (but similar problems on OS X with latest version):

```console
root@hexagon:/tmp# umount root/
root@hexagon:/tmp# bindfs / root
root@hexagon:/tmp# cat /dev/null
root@hexagon:/tmp# cat root/dev/null 
cat: root/dev/null: Permission denied
```

If this is solvable I might try to submit a patch, so will look into code soon if I have time. If this is not solvable this limitation should be documented.

**Comment by mpartel** [comment]
Looks like `-odev` makes it work. FUSE mounts with `-onodev` by default. I agree, this should be documented. I'll do so.

**Comment by itamarst** [comment]
Thanks! Doesn't seem to do the trick on OS X, unfortunately.

**Comment by mpartel** [comment]
Oh, that's unfortunate. I'll note that on the man page.

**Comment by itamarst** [comment]
Thank you!
