### ISSUE TITLE
Expose block device as regular file

### ISSUE THREAD

**Issue by msg7086** [mpartel/bindfs#53]
Hello,

Is it possible to, not only resolve the symbolic links, but also expose the target as a regular file if it's a block device?

For example, `ln -s /dev/sdb2 /export/sdb2` and then I want to access `sdb2` remotely though an NFS share.

Or is there any other alternative fuse that I should try?

Thanks!

**Comment by mpartel** [comment]
Good idea. Done with `--block-devices-as-files` in 1.13.7.

**Comment by msg7086** [comment]
Wow that's quick! Thank you so much!
