### ISSUE TITLE
Software caused connection abort when accessing a nested FUSE mount

### ISSUE THREAD

**Issue by mengelmann** [mpartel/bindfs#54]
I've encountered an issue with listing directory that is a nested FUSE mount (BorgBackup specifically). I'm getting "Software caused connection abort" error when accessing hierarchy: 
/bindfs-mount/borg-mount

I'm not sure if it's the issue with bindfs or with Borg. 

**How to reproduce:**
1. Download latest stable Borg binary https://github.com/borgbackup/borg/releases/tag/1.0.10

2. Initialize Borg repository
```
# mkdir -p /tmp/test/{source,borg-repository,borg-mount}
# touch /tmp/test/source/{a,b,c} 
# borg init --encryption none /tmp/test/borg-repository
```

3. Create backup
```
# borg create /tmp/test/borg-repository::{now} /tmp/test/source/
```

4. Mount Borg repository via FUSE (foreground & debug)
```
# borg mount -f --debug /tmp/test/borg-repository /tmp/test/borg-mount
```

5. Mount bindfs (foreground & debug)
```
# mkdir /tmp/bindfs-mount
# bindfs -f -d /tmp/test /tmp/bindfs-mount
```

6. **WORKS**: Listing normal directory
```
# ls -l /tmp/bindfs-mount/borg-repository
```

7. **DOES NOT WORK**: Listing nested mount (output from foreground mount below)
```
# ls -l /tmp/bindfs-mount/borg-mount
ls: reading directory /tmp/bindfs-mount/borg-mount/: Software caused connection abort
total 0
```

```
# ls -l /tmp/bindfs-mount
ls: cannot access /tmp/bindfs-mount: Transport endpoint is not connected
```

**Output from borg mount:**
```
using builtin fallback logging configuration
TAM-verified manifest
mount data cache capacity: 2 chunks
Mounting filesystem
Initializing llfuse
Calling fuse_mount
Calling fuse_lowlevel_new
Calling fuse_session_add_chan
Calling fuse_session_loop
```

**Output from bindfs mount:**
```
FUSE library version: 2.9.3
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.25
flags=0x0007fffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 36621
getattr /
   unique: 2, success, outsize: 120
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 36621
LOOKUP /borg-mount
getattr /borg-mount
   NODEID: 2
   unique: 3, success, outsize: 144
unique: 4, opcode: GETXATTR (22), nodeid: 2, insize: 65, pid: 36621
getxattr /borg-mount security.selinux 255
   unique: 4, error: -61 (No data available), outsize: 16
unique: 5, opcode: GETXATTR (22), nodeid: 2, insize: 72, pid: 36621
getxattr /borg-mount system.posix_acl_access 0
   unique: 5, error: -61 (No data available), outsize: 16
unique: 6, opcode: GETXATTR (22), nodeid: 2, insize: 73, pid: 36621
getxattr /borg-mount system.posix_acl_default 0
   unique: 6, error: -61 (No data available), outsize: 16
unique: 7, opcode: OPENDIR (27), nodeid: 2, insize: 48, pid: 36621
   unique: 7, success, outsize: 32
unique: 8, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 36621
readdir[0] from 0
*** Error in `bindfs': free(): invalid next size (fast): 0x00000000024ba640 ***
Aborted
```

**Comment by mpartel** [comment]
Thanks for the detailed report! It does look like a bindfs (or possibly FUSE) bug.

The `readdir` implementation has been very troublesome recently and it has seen a number changes not so long ago. Looks like it's still not quite there yet :(

I'll try to find time to debug properly.

**Comment by mengelmann** [comment]
@mpartel please let me know if I can help (more tests, debug).

**Comment by mpartel** [comment]
Reproducing with bindfs running under [valgrind](http://valgrind.org/) might give a useful backtrace.

**Comment by mpartel** [comment]
Workaround committed to master. The bug was that not enough space was allocated to directory entries, because `pathconf(real_path, _PC_NAME_MAX)` on a path inside a borg mount returns 0, which according to its (and `readdir`'s) documentation it really shouldn't. Bindfs now assumes `NAME_MAX` (255 on my system) as the maximum filename length in that case. I'll file a bug to borg as well.

**Comment by marcindulak** [comment]
I experienced this problem with https://github.com/kahing/goofys/issues/236

Are there any plans for a new bindfs release (and an update in Fedora/EPEL)?

**Comment by mpartel** [comment]
Whoops, sorry! 1.13.8 released now.
