### ISSUE TITLE
Size of filesystem reported with 0 on macOS 10.13 GM and osxfuse 3.7.0

### ISSUE THREAD

**Issue by Bleistein** [mpartel/bindfs#58]
On macOS 10.13 Beta (17A362a) bindfs 1.13.7 will report a capacity of 0 of the mounted filesystem when used with osxfuse 3.7.0. The mount point filesystem is APFS.

Rolling back to osxfuse 3.6.3 shows the correct filesystem sizes again.

**Comment by mpartel** [comment]
FTR discussion at https://github.com/osxfuse/osxfuse/issues/414

**Comment by mpartel** [comment]
Looks like it turned out to be an osxfuse bug. Closing this. Thanks for reporting!
