### ISSUE TITLE
'Device or resource busy' AFTER a successful umount

### ISSUE THREAD

**Issue by Aftek** [mpartel/bindfs#64]
Hi,

I'm having a weird issue that appeared only this week,
used to work without issue..

with a cPanel server on cloudlinux and cagefs enabled,
I'm sharing a directory to multiple users.

This actually seems to still work as expected..
but when the user is to be deleted, after the umount, the directory stays "busy"..
and the user's home directory cannot be removed completely unless the server is rebooted.

Here's what my fstab looks like:
```
/home/share/files    /home/test9/files    fuse.bindfs    map=1015/1060:@1017/@1062    0    0
/home/share/files    /home/test10/files    fuse.bindfs    map=1015/1061:@1017/@1063    0    0
/home/share/files    /home/test11/files    fuse.bindfs    map=1015/1062:@1017/@1064    0    0
/home/share/files    /home/test12/files    fuse.bindfs    map=1015/1063:@1017/@1065    0    0
/home/share/files    /home/test13/files    fuse.bindfs    map=1015/1064:@1017/@1066    0    0
/home/share/files    /home/test14/files    fuse.bindfs    map=1015/1065:@1017/@1067    0    0
/home/share/files    /home/test15/files    fuse.bindfs    map=1015/1066:@1017/@1068    0    0
/home/share/files    /home/test16/files    fuse.bindfs    map=1015/1067:@1017/@1069    0    0
#/home/share/files    /home/test16/files    fuse.bindfs    nodev,nosuid,noatime,force-user=test16,force-group=test16    0    0
```
the last line is me trying different options without any success so far..

Let's try to remove the user 'test13':

### 1. while it is still mounted and working as expected, fuser will show:
```
# fuser -vm /home/test13/files
                     USER        PID ACCESS COMMAND
/home/test13/files:
                     root     kernel mount /home/test13/files
```
### 2. proceed with the umount
`# umount /home/test13/files`
I also tried those, but I'm getting the same 'busy' error at the end:
`# umount -f /home/test13/files`
`# umount -l /home/test13/files`
`# fusermount -u /home/test13/files`
`# fusermount -z -u /home/test13/files`

### 3. there's an extra step with cagefs enabled
at this point, root sees the mount point empty (  with a simple `# ls -la /home/test13/files` )
but for the user to see it, we need to:
`# cagefsctl --remount test13`
or
`# cagefsctl --remount-all`

### 4. and this is where it all goes down.. removing the mount point:
```
# rm -rf /home/test13/files
rm: cannot remove ‘/home/test13/files’: Device or resource busy
```

### 5. the mount point is now empty, but to confirm I ran:
```
# umount /home/test13/files
umount: /home/test13/files: not mounted

# cat /proc/mounts | grep test13
( no output )
```

### 6. now the reason I created this issue here is because of the new output from fuser:
```
# fuser -vm /home/test13/files
                     USER        PID ACCESS COMMAND
/home/test13/files:
                     root     kernel mount /home
                     root       3586 f.c.. bindfs
                     root       3588 f.c.. bindfs
                     root       3590 f.c.. bindfs
                     root       3592 f.c.. bindfs
                     root       3596 f.c.. bindfs
                     root       3598 f.c.. bindfs
                     root       3600 f.c.. bindfs
```
these are the bindfs' PID of all the other mounts still active.
```
# ps aux | grep bindfs
root      3586  0.0  0.0  13616   492 ?        Ss   10:33   0:00 bindfs /home/share/files /home/test9/files -o rw,map=1015/1060:@1017/@1062,dev,suid
root      3588  0.0  0.0  13616   492 ?        Ss   10:33   0:00 bindfs /home/share/files /home/test10/files -o rw,map=1015/1061:@1017/@1063,dev,suid
root      3590  0.0  0.0  13616   492 ?        Ss   10:33   0:00 bindfs /home/share/files /home/test11/files -o rw,map=1015/1062:@1017/@1064,dev,suid
root      3592  0.0  0.0  13616   492 ?        Ss   10:33   0:00 bindfs /home/share/files /home/test12/files -o rw,map=1015/1063:@1017/@1065,dev,suid
root      3596  0.0  0.0  13616   492 ?        Ss   10:33   0:00 bindfs /home/share/files /home/test14/files -o rw,map=1015/1065:@1017/@1067,dev,suid
root      3598  0.0  0.0  13616   492 ?        Ss   10:33   0:00 bindfs /home/share/files /home/test15/files -o rw,map=1015/1066:@1017/@1068,dev,suid
root      3600  0.0  0.0  13616   696 ?        Ss   10:33   0:00 bindfs /home/share/files /home/test16/files -o rw,map=1015/1067:@1017/@1069,dev,suid
```
lsof has similar output too:
```
# lsof | grep 'share/files'
bindfs     3586                     root  cwd       DIR              253,2      4096 1073752629 /home/share/files
bindfs     3586                     root    3r      DIR              253,2      4096 1073752629 /home/share/files
bindfs     3588                     root  cwd       DIR              253,2      4096 1073752629 /home/share/files
bindfs     3588                     root    3r      DIR              253,2      4096 1073752629 /home/share/files
bindfs     3590                     root  cwd       DIR              253,2      4096 1073752629 /home/share/files
bindfs     3590                     root    3r      DIR              253,2      4096 1073752629 /home/share/files
bindfs     3592                     root  cwd       DIR              253,2      4096 1073752629 /home/share/files
bindfs     3592                     root    3r      DIR              253,2      4096 1073752629 /home/share/files
bindfs     3596                     root  cwd       DIR              253,2      4096 1073752629 /home/share/files
bindfs     3596                     root    3r      DIR              253,2      4096 1073752629 /home/share/files
bindfs     3598                     root  cwd       DIR              253,2      4096 1073752629 /home/share/files
bindfs     3598                     root    3r      DIR              253,2      4096 1073752629 /home/share/files
bindfs     3600                     root  cwd       DIR              253,2      4096 1073752629 /home/share/files
bindfs     3600                     root    3r      DIR              253,2      4096 1073752629 /home/share/files
```

### 7. i'm still not convinced bindfs is part of the issue
I tried unmounting them all.. fuser now shows:
```
fuser -vm /home/test13/files/
                     USER        PID ACCESS COMMAND
/home/test13/files
                     root     kernel mount /home
```
and yet i'm still unable to rm the mount point.. unless there's an ugly reboot involved
```
# rm -rf /home/test13/files
rm: cannot remove ‘/home/test13/files’: Device or resource busy
```

### and now...
it used to work perfectly last week...
bindfs hasn't been updated or changed whatsoever since..
and the kernel hasn't been updated either for the path month.
there has been an update to cpanel.. ( [60.0.29 -> 60.0.30](https://documentation.cpanel.net/display/CL/68+Change+Log) ),
but I cannot see anything that looks suspicious in the changelog yet..

is there anything fishy in my steps above ? am I missing something obvious ?
at this point, even just a confirmation that bindfs has nothing to do with it would be helpful.

a tiny bit more info:
```
# bindfs --version
bindfs 1.13.8

# uname -a
Linux example.com 3.10.0-714.10.2.lve1.4.79.el7.x86_64 #1 SMP Thu Jan 4 13:30:50 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mpartel** [comment]
Very strange. I'm not familiar with cagefs, but I can partially explain (6): bindfs keeps an FD to the source directory (`/home/share/files`) open while it's running. I have no idea why `fuser` shows the bindfs processes for the other mountpoints holding `/home/test13/files` open.

At the moment bindfs seems unlikely to be the direct culprit since the bindfs process for `test13` seems to have been shut down by your unmount command(s). Could you double-check that this is the case?

A random idea: could there be a race condition where cagefs starts and does its thing (perhaps only partially) before bindfs starts, or vice versa? What happens if you e.g. inject a sleep to the startup script of one or the other?

**Comment by Aftek** [comment]
I'm still not that familiar with cagefs either,
spent the day trying to learn more and still no solutions..

> [...] the bindfs process for test13 seems to have been shut down by your unmount command(s). Could you 
> double-check that this is the case?

The process for test13 was actually not being shutdown by the unmount command right away,
it would only go away after a `cagefsctl --remount test13`..

but I upgraded the kernel to `3.10.0-714.10.2.lve1.5.12.el7.x86_64` and now after a reboot, the bindfs process for test13 seems to remain there even after a `cagefs --remount-all`.. and `fuser -vm` still shows the process ID for all bindfs currently running...
and yet, the mountpoint `/home/test13/files` does not appear to be not mounted and is empty for both root and test13.

> [...] could there be a race condition where cagefs starts and does its thing [...]

at this point, I'm not even sure how cagefs starts at all..
with a reboot, all mounts in /etc/fstab are working as expected;
it's only the removal that's causing issues..
whether it was mounted on boot, or later, manually or via script,
I'm getting the same results.

I'm going to try and contact cloudlinux support first thing in the morning.
they do release their own kernel to provide features like cagefs after all..
if the actual mount/unmount seem to work, it could make sense that this additional cagefs layer is the culprit.
I was unable to reproduce the issue on ubuntu 16.04 or centos 7, and the only real difference  in 48hrs is after a kernel update ( not such a good one too,  since the bindfs process for test13 seems to stay alive now ).


I also tried:
`sync`
waiting a few seconds/minutes and then
`echo 3 > /proc/sys/vm/drop_caches`
but still the same `cannot remove ‘/home/test13/files’: Device or resource busy`

**Comment by mpartel** [comment]
> The process for test13 was actually not being shutdown by the unmount command right away,
it would only go away after a cagefsctl --remount test13..

You may have tried this already, but since cagefs appears to be some sort of container-like thing, I wonder if doing `fuser`/`lsof` *inside* the user's container would tell us what's keeping `/home/test13/files` open.

**Comment by Aftek** [comment]
Thought I had, but `fuser` and `lsof` were not available to users inside cagefs..
after adding it and logging in via ssh directly to test13 ( no more `su - test13` ):

`lsof` or `lsof +D`.. still empty.
and `fuser` shows:
```
$ fuser -vm files/
                     USER        PID ACCESS COMMAND
/home/test13/files:
                     root     kernel mount /opt/alt/php56/link
                     test13   9939 ..c.. bash
```
I did not expect `/opt/alt/php56/link`..
I'll have to look into it a bit more and update this issue if I find anything..

also, `test13   9939 ..c.. bash` seems to say `/home/test13/files` is test13's current working directory..
while `fuser` was run from `/home/test13`.. 

so, two lines I find suspicious and worth investigating..
to be continued.. thanks for your help so far, much appreciated!

**Comment by Aftek** [comment]
Still a bit of a mystery to me how it worked and now it requires this, but thanks to cloudlinux support,
we figured out that some processes still had the mounts active in their own mount namespace ( all of this is still quite new to me ).

executing `grep -rl <mount_point_path> /proc/*/mounts`
will give you the list of PID with the mount still active in their own namespaces..

then, `nsenter -m -t <PID> cat /proc/mounts | grep <mount_point_path>`
just confirms it is still mounted for that process/PID.

so for each pid given by the first `grep` in `/proc/*/mounts` , just run:
`nsenter -m -t <PID> umount <mount_point_path>`

Once all of the PIDs have had it unmounted, `rm -rf` on the empty directory worked without a reboot.

Thanks again for your support here.. much appreciated!
I'll close this issue now..
( but I'm still secretly hoping to get a real solution rather than a workaround.. but for now, it's working, so no complaining : )

**Comment by mpartel** [comment]
I'm not familiar with mount namespaces but I guess it makes sense that you can't unmount something that's still in use, even if the user is sort-of hidden.

Glad you found a solution!
