### ISSUE TITLE
bindfs - Doesn't work for folder inside “/proc/[docker pid]/root”

### ISSUE THREAD

**Issue by belonesox** [mpartel/bindfs#66]
For each docker container, internal docker container filesystem exposed as "/proc/[docker Pid]/root/"

```
stas-custis-desktop stas # docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
a8206d03d844        mageia              "/bin/bash"         4 days ago          Up 4 days                               gifted_fermi
stas-custis-desktop stas # ls -l "/proc/$(docker inspect --format {{.State.Pid}} a8206)/root/"
итого 56
lrwxrwxrwx   1 root root    7 фев 11  2016 bin -> usr/bin/
drwxr-xr-x   2 root root 4096 фев 11  2016 boot/
drwxr-xr-x   3 root root 4096 апр 25 08:44 code/
drwxr-xr-x   5 root root  360 окт  4 17:59 dev/
drwxr-xr-x  59 root root 4096 окт  4 18:00 etc/
drwxr-xr-x   2 root root 4096 фев 11  2016 home/
drwxr-xr-x   2 root root 4096 фев 11  2016 initrd/
lrwxrwxrwx   1 root root    7 фев 11  2016 lib -> usr/lib/
lrwxrwxrwx   1 root root    9 фев 11  2016 lib64 -> usr/lib64/
drwxr-xr-x   2 root root 4096 фев 11  2016 media/
drwxr-xr-x   2 root root 4096 фев 11  2016 mnt/
drwxr-xr-x   2 root root 4096 фев 11  2016 opt/
dr-xr-xr-x 325 root root    0 окт  4 17:59 proc/
drwxr-x---   3 root root 4096 окт  4 17:59 root/
drwxr-xr-x   9 root root 4096 апр 25 08:45 run/
lrwxrwxrwx   1 root root    8 фев 11  2016 sbin -> usr/sbin/
drwxr-xr-x   2 root root 4096 фев 11  2016 srv/
dr-xr-xr-x  13 root root    0 окт  4 17:59 sys/
drwxrwxrwt   7 root root 4096 окт  4 18:00 tmp/
drwxr-xr-x  19 root root 4096 окт  4 18:00 usr/
drwxr-xr-x  18 root root 4096 окт  4 18:00 var/
```

But when I try to mount it with bindfs, I got mount to my own root filesystem.
```
stas-custis-desktop stas # mkdir /mnt/testbindfs
stas-custis-desktop stas # bindfs "/proc/$(docker inspect --format {{.State.Pid}} a8206)/root/" /mnt/testbindfs/
stas-custis-desktop stas # ls /mnt/testbindfs/
bin/   cgroup/  dev/  fastprojects/   home/  initrd/  lib64/       media/  Module.symvers  proc/  run/   scaner/  sys/  U/   usr/  X/   Z/   Z3/
boot/  data/    etc/  fastprojects2/  I/     lib/     lost+found/  mnt/    opt/            root/  sbin/  srv/     tmp/  U2/  var/  X2/  Z2/
stas-custis-desktop stas # ls /
bin/   cgroup/  dev/  fastprojects/   home/  initrd/  lib64/       media/  Module.symvers  proc/  run/   scaner/  sys/  U/   usr/  X/   Z/   Z3/
boot/  data/    etc/  fastprojects2/  I/     lib/     lost+found/  mnt/    opt/            root/  sbin/  srv/     tmp/  U2/  var/  X2/  Z2/
stas-custis-desktop stas # 
```

Why? Can this be fixed?

```
docker 17.05.0
bindfs 1.13.9
```
Tested on Debiand and RPM-based Linux.  Problem looks well known https://stackoverflow.com/questions/49565598/bindfs-doesnt-work-for-folder-inside-proc

**Comment by mpartel** [comment]
Hmm, this is surprising, since bindfs just `chdir`s into the source directory and resolves pathnames relative to that. Does `bindfs -d` (run in foreground and show debug output) show anything strange?

I'll try to repro and take a closer look tonight.
Thanks for reporting!

**Comment by mpartel** [comment]
Ok, that `root` directory seems to be some sort of magic fake symlink:
```
$ sudo ls -l /proc/$(docker inspect --format {{.State.Pid}} bd5dee389782)/root
lrwxrwxrwx 1 root root 0 Oct  9 19:18 /proc/17018/root -> /
```
but
```
$ sudo ls -l /proc/$(docker inspect --format {{.State.Pid}} bd5dee389782)/root/
<stuff inside the container>
```

bindfs calls `realpath` on the source directory, turning it into `/`, and I'd rather not remove that call. I'll add a special case for `/proc/`. Just a moment.

**Comment by mpartel** [comment]
Workaround added and 1.13.10 released. Let me know if it doesn't work for you.

**Comment by nishantvarma** [comment]
This doesn't seem to work when it the `proc` directory is in the RHS?

**Comment by mpartel** [comment]
Example?

**Comment by nishantvarma** [comment]
I am sorry, I am able to mount from container to host:

`sudo bindfs /proc/1199/root/tmp test && ls test && sudo umount test;`

but not the other way:

` sudo bindfs test /proc/1199/root/test && ls /proc/1199/root/test && sudo umount /proc/1199/root/test`

(assumes `test` folder exists in current working directory.)

**Comment by mpartel** [comment]
I have a feeling this might not be possible, at least not through `/proc` like that. Bindfs doesn't do anything to the destination directory by itself. FUSE / the kernel creates the mountpoint and forwards requests to bindfs, which bindfs then handles by operating on the source directory. If bindfs never receives these requests, then the problem is elsewhere.

Does `mount --bind` with the same `/proc/...` paths work as expected? If it does, I'd be surprised and would wonder why FUSE works differently. If not, I think the next step would be to figure out how docker does its bind mounts.

**Comment by nishantvarma** [comment]
I tried that:

```
% sudo mount --bind test /proc/<pid>/root/test
mount: /proc/<pid>/root/test: wrong fs type, bad option, bad superblock on /home/nishant/test, missing codepage or helper program, or other error.
```

I am really new to this.

**Comment by nishantvarma** [comment]
@mpartel , Do you want me to send an the MR for `readlink` issue in `mntdest`, just to be in sync with `mntsrc`?

I am trying a hack to solve this problem: 

1. Mount `src` using docker's default bind mount.
2. Do a `bindfs` **inside** the container to **itself**: `sudo bindfs --map=1000/2000:@1000/2000 /usr/src /usr/src`. It seems to work, but there are any caveats? It seems very hacky, but saves a lot of time.

**Comment by mpartel** [comment]
Sorry, I'm sometimes slow at looking at these.

I wouldn't add the `/proc` hack to `mntdest` unless there's a use case where it works in practice.

Your approach seems reasonable to me. I don't know what a solution outside the container would look like, but there's a good chance it'd feel at least as hacky.

Someone has written a docker plugin for bindfs, although it looks unmaintained (not sure if it needs that much maintenance): https://github.com/lebokus/docker-volume-bindfs

Finally, someone has written a detailed blogpost about this topic: https://www.joyfulbikeshedding.com/blog/2021-03-15-docker-and-the-host-filesystem-owner-matching-problem.html

**Comment by nishantvarma** [comment]
Thank you, appreciate your help! I will check out these suggestions. Without `bindfs`, this problem looked incredibly difficult to solve.
