### ISSUE TITLE
Feature: automatically rmdir destination dir on exit

### ISSUE THREAD

**Issue by mpartel** [mpartel/bindfs#70]
Sometimes it's less error prone to have a missing directory rather than an empty directory.

**Comment by slonopotamus** [comment]
bindfs doesn't create target dir, so why would it remove one? It's not symmetrical.

**Comment by mpartel** [comment]
You're right, it should optionally mkdir too.

Anyway, perhaps this feature would indeed be a bit pointless, because a crash can always leave an empty directory behind.
