### ISSUE TITLE
resolve-symlinks causes du to crash with a core dump

### ISSUE THREAD

**Issue by redneb** [mpartel/bindfs#76]
When I create a `bindfs` mount with the `--resolve-symlinks` option, and if the source directory contains at least one symlink to a directory, then I cannot run `du` on the `bindfs` mount directory, it crashes with a core dump. Here's a simple way to reproduce this:

    mkdir -v /tmp/bindfs-test/{,src,dest,test}
    ln -sv /tmp/bindfs-test/{test,src/test}
    bindfs --no-allow-other --resolve-symlinks /tmp/bindfs-test/{src,dest}
    du -hs /tmp/bindfs-test/dest

I have tried this on two different x86_64 linux boxes with the same results.

**Comment by redneb** [comment]
And here's an strace of the offending command:

    $ strace du /tmp/bindfs-test/dest
    execve("/usr/bin/du", ["du", "/tmp/bindfs-test/dest"], 0x7fffc0389f48 /* 70 vars */) = 0
    brk(NULL)                               = 0x559d56a55000
    access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
    openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    fstat(3, {st_mode=S_IFREG|0644, st_size=259364, ...}) = 0
    mmap(NULL, 259364, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff796427000
    close(3)                                = 0
    openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20@\2\0\0\0\0\0"..., 832) = 832
    fstat(3, {st_mode=S_IFREG|0755, st_size=1902040, ...}) = 0
    mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff796425000
    mmap(NULL, 1914880, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff796251000
    mmap(0x7ff796273000, 1433600, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7ff796273000
    mmap(0x7ff7963d1000, 303104, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x180000) = 0x7ff7963d1000
    mmap(0x7ff79641b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c9000) = 0x7ff79641b000
    mmap(0x7ff796421000, 14336, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ff796421000
    close(3)                                = 0
    arch_prctl(ARCH_SET_FS, 0x7ff796426580) = 0
    mprotect(0x7ff79641b000, 16384, PROT_READ) = 0
    mprotect(0x559d5611b000, 4096, PROT_READ) = 0
    mprotect(0x7ff79648f000, 4096, PROT_READ) = 0
    munmap(0x7ff796427000, 259364)          = 0
    brk(NULL)                               = 0x559d56a55000
    brk(0x559d56a76000)                     = 0x559d56a76000
    openat(AT_FDCWD, "/usr/lib64/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
    fstat(3, {st_mode=S_IFREG|0644, st_size=4559216, ...}) = 0
    mmap(NULL, 4559216, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff795df7000
    close(3)                                = 0
    newfstatat(AT_FDCWD, "/tmp/bindfs-test/dest", {st_mode=S_IFDIR|0755, st_size=8, ...}, AT_SYMLINK_NOFOLLOW) = 0
    openat(AT_FDCWD, "/tmp/bindfs-test/dest", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 3
    fstat(3, {st_mode=S_IFDIR|0755, st_size=8, ...}) = 0
    fcntl(3, F_GETFL)                       = 0x38800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
    fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
    newfstatat(AT_FDCWD, "/tmp/bindfs-test/dest", {st_mode=S_IFDIR|0755, st_size=8, ...}, AT_SYMLINK_NOFOLLOW) = 0
    fcntl(3, F_DUPFD_CLOEXEC, 3)            = 4
    getdents64(3, /* 3 entries */, 32768)   = 72
    getdents64(3, /* 0 entries */, 32768)   = 0
    close(3)                                = 0
    newfstatat(4, "test", {st_mode=S_IFDIR|0755, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
    openat(4, "test", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 3
    fstat(3, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
    fcntl(3, F_GETFL)                       = 0x38800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
    fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
    rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
    rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
    getpid()                                = 18371
    gettid()                                = 18371
    tgkill(18371, 18371, SIGABRT)           = 0
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=18371, si_uid=1000} ---
    +++ killed by SIGABRT (core dumped) +++
    Aborted (core dumped)

**Comment by mpartel** [comment]
Thanks! Fixed in 1.14.1!
