### ISSUE TITLE
bindfs over NFS shows the underlying file system

### ISSUE THREAD

**Issue by alkisg** [mpartel/bindfs#78]
I'm not sure if this is an NFS issue, or a bindfs issue, and if a workaround can be found in either of them.

I export my /home via NFS with:
> /home	*(rw,async,crossmnt,no_subtree_check,no_root_squash,insecure)

Inside my /home I'm providing a shared folder with a bindfs mount:
> bindfs -u 1000 --create-for-user=1000 -g 100 --create-for-group=100 -p 770,af-x /home/share /home/share

And finally I mount /home on some NFS client (or on localhost):
> mount -t nfs server:/home /home

The problem is that /home/share on the client doesn't show bindfs, but it shows the underlying file system of the server's /home/share.
The crossmnt NFS option follows submounts with other file systems, but not with bindfs.

On the other hand, if the bindfs source is on a different file system than the bindfs target directory, everything works fine (i.e. `bindfs /other/filesystem/share /home/share`).

Is there any way to configure either NFS or bindfs, so that this works when the share is on the same file system as /home?

Thank you!

**Comment by mpartel** [comment]
I don't know NFS very well, but searching the internet for "nfs crossmnt fuse" suggests NFS has trouble with all FUSE filesystems, not just bindfs. [This answer](https://unix.stackexchange.com/a/150727/20296) claims you need NFSv4 to make it work.

Hope this gives you some leads! I'll close this, but please reopen if it turns out some change in bindfs could help.

**Comment by alkisg** [comment]
Thank you for the feedback. I had read that answer, it's only partially correct:

If I explicitly list /home/share in exports, then I do need to specify an fsid.
If I specify an fsid, I can still use NFS3, and everything works fine (while the answer mentions that NFS4 is needed).

> 476 29 0:65 / /mnt rw,relatime shared:311 - nfs localhost:/home/share rw,vers=3,rsize=...


But I shouldn't even have to specify /home/share in exports at all; /home/share should have been automatically exported with a different fsid, as its parent, /home, is listed with the crossmnt parameter.

I think the main question here is "why can't NFS automatically detect/assign an fsid for bindfs?"
And the subquestion "where should that be fixed, in NFS or in bindfs?"

If I ever find the answer to these questions, I'll update this issue. Thanks again!
