### ISSUE TITLE
Numerical UID/GID requires “/etc/{passwd,group}” to exist

### ISSUE THREAD

**Issue by mirfatif** [mpartel/bindfs#79]
Are there any security concerns going other way? This is problematic on Android where `/etc` is on a read-only filesystem protected by `dm-verity` which needs to be disabled or some bind mount trick has to be used to create both files.

Use case: https://android.stackexchange.com/a/217936/218526

**Comment by mpartel** [comment]
Removed the check and released as 1.14.2. I'm almost certain I had intended it as check against accidental misuse and I hadn't considered enviornments like this.

Thanks!

**Comment by mirfatif** [comment]
@mpartel thanks to you for the quick response. Another thanks for the good project.
