### ISSUE TITLE
Failed to resolve mount point  on MacOS / Catalina

### ISSUE THREAD

**Issue by thomasd3** [mpartel/bindfs#83]
mkdir aa
mkdir bb
bindfs aa bb

gives:
Failed to resolve mount point `bb': No such file or directory

**Comment by mpartel** [comment]
Looks like Apple broke `realpath()` in Catalina unless a specific symbol is defined: https://github.com/JuliaLang/julia/issues/33545 & https://github.com/deepmind/lab/issues/173

Should be fixed in bindfs 1.14.4. Or you can probably use absolute paths as a workaround.

Thanks!

**Comment by OverHealz** [comment]
This issue exists on Ventura now
