### ISSUE TITLE
Not working on Mac OS Big Sur

### ISSUE THREAD

**Issue by BYVoid** [mpartel/bindfs#92]
`brew install bindfs` (Downloading https://homebrew.bintray.com/bottles/bindfs-1.14.8.catalina.bottle.tar.gz)

When I tried to run bindfs, the error was:

```
kext load failed: -603947007
mount_osxfuse: the file system is not available (255)
```

**Comment by mpartel** [comment]
That error is something that must be addressed at the macFUSE level. It has been discussed [here](https://github.com/osxfuse/osxfuse/issues/741) and there seem to be some workarounds already.

Closing, but please reopen if there are other problems after getting the kext to load, especially if e.g. sshfs works but bindfs doesn't.
