### ISSUE TITLE
Can bind file to directory without error

### ISSUE THREAD

**Issue by jeremybobbin** [mpartel/bindfs#93]
```
mkdir d
touch f
bindfs f d
```

The `bindfs f d` returns 0.
Is this the intended behavior?

**Comment by mpartel** [comment]
Nope. Fixed in master. Thanks!

Weirdly, libfuse lets bindfs mount a directory to a file. The file then returns I/O error on any operations that I thought of trying. Strange, but I'm inclined to leave it as-is, because maybe libfuse has a reason :man_shrugging:

**Comment by mpartel** [comment]
1.14.9 released with this fix in it.
