### ISSUE TITLE
permchain: older gcc cannot handle struct permchain with c99

### ISSUE THREAD

**Issue by barsnick** [mpartel/bindfs#97]
Trying to compile bindfs with older gcc, there is an issue with the interpretation of struct permchain:
```
gcc -DHAVE_CONFIG_H -I. -I..  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=700 -D__BSD_VISIBLE=1 -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_DARWIN_BETTER_REALPATH -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse     -Wall -fno-common -std=c99 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -MT permchain.o -MD -MP -MF .deps/permchain.Tpo -c -o permchain.o permchain.c
permchain.c:39: warning: declaration does not declare anything
permchain.c: In function 'permchain_create':
permchain.c:48: error: 'struct permchain' has no member named 'operands'
permchain.c:48: error: 'struct permchain' has no member named 'operands'
permchain.c: In function 'add_chmod_rule_to_permchain':
permchain.c:74: error: 'struct permchain' has no member named 'operands'
permchain.c:125: error: 'struct permchain' has no member named 'operands'
permchain.c:125: error: 'struct permchain' has no member named 'operands'
permchain.c:125: error: 'struct permchain' has no member named 'operands'
permchain.c: In function 'add_octal_rule_to_permchain':
permchain.c:162: error: 'struct permchain' has no member named 'octal'
permchain.c: In function 'permchain_apply':
permchain.c:256: error: 'struct permchain' has no member named 'operands'
permchain.c:306: error: 'struct permchain' has no member named 'octal'
make[2]: *** [permchain.o] Error 1
```

This is with gcc 4.4.7 on RHEL6, the same happens with 4.3.2 (yeah, ancient). Removal of ```-std=c99``` makes this unit compile successfully, but the remaining code of bindfs needs C99 for some code features.

Perhaps this is a gcc bug in its (old) C99 support. But perhaps the union inside the struct just needs to be declared differently for it to work with C99 and these compilers.

**Comment by mpartel** [comment]
Should be fixed in 1.15.1.
Thanks!

**Comment by barsnick** [comment]
Nice, thanks!

Small remark: ```-Wpedantic``` was introduced with gcc-4.8. For older versions, only ```-pedantic``` is valid. (I needed to patch configure*). I understand the latter is deprecated, but still works.

I don't want to burden you with configure.ac checks for validity of compiler flags. So, "just sayin'".

**Comment by mpartel** [comment]
> I don't want to burden you with configure.ac checks for validity of compiler flags.

I'd accept a PR if you'd like to burden yourself instead :)

I used to test against centos 6 until [recently](https://github.com/mpartel/bindfs/commit/abec828272e37e4768f7a48a469e213dd270d358), but they seem to have removed its YUM repos, apparently because it has [EOL'ed](https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule).
