### ISSUE TITLE
M1 MacBook Compatibility

### ISSUE THREAD

**Issue by lxchtan** [mpartel/bindfs#99]
osxfuse 3.x is no longer supported by M1 (osxfuse/osxfuse#754), will bindfs be able to compile on macfuse 4.x? 
I have already install macfuse 4.1.0. When I ran the command,`brew install bindfs`, it complained

> Warning: bindfs has been deprecated because it requires FUSE!
> bindfs: FUSE for macOS is required for this software. OsxfuseRequirement unsatisfied!
> You can install the necessary cask with:
>   brew install --cask osxfuse
> You can download from:
>   https://osxfuse.github.io/
> Error: An unsatisfied requirement failed this build.

I also tried to build from source, but the `./configure` showed

> checking for fuse3 >= 3.4.0... no
> checking for fuse >= 2.9.0... no
> checking for fuse >= 2.8.0... no
> configure: error: FUSE not found.

Is it any way to make it work with M1 Macbook, or just with macfuse 4.1.0?

**Comment by mpartel** [comment]
I just upgraded macfuse from 3.something to 4.1.0 on my mac (still running Catalina).
- `./configure` still passes (it finds `fuse` but not `fuse3`)
- bindfs now crashes with "Illegal instruction: 4". Maybe macfuse no longer supports Catalina ¯\\_(ツ)_⁄¯
- I don't have an M1 to test with (I rarely use macs voluntarily..)

Does `config.log` show anything interesting after "checking for fuse >= 2.9.0"?

**Comment by lxchtan** [comment]
This is `config.log` around "checking for fuse >= 2.9.0".
> configure:4597: checking for pkg-config
> configure:4620: found /opt/homebrew/bin/pkg-config
> configure:4632: result: /opt/homebrew/bin/pkg-config
> configure:4657: checking pkg-config is at least version 0.9.0
> configure:4660: result: yes
> configure:4990: checking for fuse3 >= 3.4.0
> configure:4997: $PKG_CONFIG --exists --print-errors "fuse3 >= 3.4.0"
> Package fuse3 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `fuse3.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'fuse3' found
> configure:5000: $? = 1
> configure:5014: $PKG_CONFIG --exists --print-errors "fuse3 >= 3.4.0"
> Package fuse3 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `fuse3.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'fuse3' found
> configure:5017: $? = 1
> configure:5031: result: no
> No package 'fuse3' found
> configure:5049: checking for fuse >= 2.9.0
> configure:5056: $PKG_CONFIG --exists --print-errors "fuse >= 2.9.0"
> Package fuse was not found in the pkg-config search path.
> Perhaps you should add the directory containing `fuse.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'fuse' found
> configure:5059: $? = 1

**Comment by mpartel** [comment]
Have you installed xcode and the command line developer tools? Maybe you need to run `xcode-select --install` (I had to after an xcode update).

Also, setting `PKG_CONFIG_PATH` as instructed [here](https://github.com/osxfuse/osxfuse/wiki/FAQ#51-i-am-having-problem-fill-in-problem-here-compiling-a-fuse-file-system-in-the-macfuse-environment-what-to-do) might help.

**Comment by lxchtan** [comment]
Hello, I found `fuse.pc` in `/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/fuse/fuse.pc` and link to `/usr/local/lib/pkgconfig/fuse.pc`. However, `ls /usr/local/lib/pkgconfig` cannot see `fuse.pc`.

So I reinstall macfuse through `brew reinstall macfuse`, and `fuse.pc` appear in `/usr/local/lib/pkgconfig`.

- Now `./configure` passes.
- bindfs works well when I build from source.
- But ` brew install bindfs`, still  complained `Error: bindfs has been disabled because it requires FUSE!`.

**Comment by mpartel** [comment]
Good to hear that it works now!

I don't maintain the [homebrew package](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bindfs.rb) but you can maybe open an issue there.
